# Generated by Django 5.1.5 on 2025-02-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_steps',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='Image', upload_to=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='name',
            field=models.CharField(default='image', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
