# Generated by Django 5.1.5 on 2025-02-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='recipes',
            field=models.ManyToManyField(related_name='categories', to='recipes.recipe'),
        ),
    ]
