# Generated by Django 5.1.5 on 2025-02-13 13:15

import django.core.validators
import recipes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=recipes.models.destination_of_preview),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_steps',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(1440), django.core.validators.MinValueValidator(5)]),
        ),
    ]
